dist: xenial
addons:
  apt:
    packages:
      - fakeroot
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  -
    file: target/debian/bintray.json
    key: $BINTRAY_KEY
    on:
      tags: true
    provider: bintray
    skip_cleanup: true
    user: pauldraper
  -
    api_key:
      secure: eykUoy/ImC0ATe30a7QBwTCgRNc4X/EGV0EpxUXY/PFk69O562kcn/fTTbw2HDWbJoUFWFV75HP/RxTOqdvp5aywghGY8YGFfhS5k1px9vg/ypLGyJYse7SHc1t24EzP6T/wlrRgb7viGkgo6vxH91MThBolLCz0GPu5UN55Tqo=
    file:
      - admin/target/*.deb
      - worker/target/**/*.jar
    file_glob: true
    on:
      tags: true
      repo: lucidsoftware/piezo
    provider: releases
    skip_cleanup: true
git:
  depth: 1
jdk:
  - openjdk8
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      if [ -z "$TRAVIS_TAG" ]; then
          sbt "compile" "test" "doc" "publishSigned"
      else
          sbt "packageBin" "packageDoc" "packageSrc" "test" "debian:bintrayDescriptor" 'sonatypeOpen piezo-$TRAVIS_TAG' "publishSigned" "sonatypeReleaseAll"
      fi
    else
      sbt "compile" "test"
    fi
